"""empty message

Revision ID: e2b4abcae5f6
Revises: bd5f63a9b78e
Create Date: 2021-03-17 11:46:59.436982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b4abcae5f6'
down_revision = 'bd5f63a9b78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('filename', sa.String(length=225), nullable=True))
    op.create_unique_constraint(None, 'property', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property', type_='unique')
    op.drop_column('property', 'filename')
    # ### end Alembic commands ###
